const test = require('brittle')
const fs = require('fs')
const os = require('os')
const path = require('path')
const PythonHyperschema = require('..')

function emptySchema() {
  return new PythonHyperschema(null, {})
}

function schemaWithStruct() {
  const hs = new PythonHyperschema(null, {})
  const ns = hs.namespace('ns')
  ns.register({
    name: 'item',
    compact: true,
    fields: [{ name: 'id', type: 'uint', required: false }]
  })
  return hs
}

function compactStructAllRequired() {
  const hs = new PythonHyperschema(null, {})
  const ns = hs.namespace('ns')
  ns.register({
    name: 'item',
    compact: true,
    fields: [{ name: 'id', type: 'uint', required: true }]
  })
  return hs
}

function compactStructWithField(typeName) {
  const hs = new PythonHyperschema(null, {})
  hs.namespace('ns').register({
    name: 'item',
    compact: true,
    fields: [{ name: 'v', type: typeName, required: true }]
  })
  return hs
}

function nonCompactStructWithBool() {
  const hs = new PythonHyperschema(null, {})
  hs.namespace('ns').register({
    name: 'b',
    compact: false,
    fields: [{ name: 'flag', type: 'bool', required: false }]
  })
  return hs
}

function schemaWithAliasField() {
  const hs = new PythonHyperschema(null, {})
  const ns = hs.namespace('ns')
  ns.register({ name: 'tag', alias: 'string' })
  ns.register({
    name: 'tagged',
    compact: false,
    fields: [{ name: 'v', type: '@ns/tag' }]
  })
  return hs
}

function schemaWithFramedNestedField() {
  const hs = new PythonHyperschema(null, {})
  const ns = hs.namespace('ns')
  ns.register({
    name: 'addr',
    compact: false,
    fields: [{ name: 'city', type: 'string', required: false }]
  })
  ns.register({
    name: 'person',
    compact: false,
    fields: [{ name: 'home', type: '@ns/addr', required: false }]
  })
  return hs
}

function schemaWithInlineNestedField() {
  const hs = new PythonHyperschema(null, {})
  const ns = hs.namespace('ns')
  ns.register({
    name: 'ts',
    compact: true,
    fields: [
      { name: 'sec', type: 'uint', required: true },
      { name: 'nsec', type: 'uint', required: true }
    ]
  })
  ns.register({
    name: 'event',
    compact: false,
    fields: [{ name: 'at', type: '@ns/ts', required: false }]
  })
  return hs
}

function schemaWithArrayOfPrimitive() {
  const hs = new PythonHyperschema(null, {})
  const ns = hs.namespace('ns')
  ns.register({ name: 'xs', array: true, type: 'uint' })
  return hs
}

function schemaWithArrayOfStruct() {
  const hs = new PythonHyperschema(null, {})
  const ns = hs.namespace('ns')
  ns.register({
    name: 'pt',
    compact: true,
    fields: [
      { name: 'x', type: 'uint', required: true },
      { name: 'y', type: 'uint', required: true }
    ]
  })
  ns.register({ name: 'pts', array: true, type: '@ns/pt' })
  return hs
}

function schemaWithRecordOfPrimitives() {
  const hs = new PythonHyperschema(null, {})
  const ns = hs.namespace('ns')
  ns.register({ name: 'm', record: true, key: 'string', value: 'uint' })
  return hs
}

function schemaWithRecordOfStructValue() {
  const hs = new PythonHyperschema(null, {})
  const ns = hs.namespace('ns')
  ns.register({
    name: 'e',
    compact: true,
    fields: [{ name: 'n', type: 'uint', required: true }]
  })
  ns.register({ name: 'r', record: true, key: 'string', value: '@ns/e' })
  return hs
}

test('empty schema emits header + resolve', (t) => {
  const code = emptySchema().toCode()
  t.ok(code.includes('autogenerated by the hyperschema-python compiler'))
  t.ok(code.includes('import compact_encoding as c'))
  t.ok(code.includes('def resolve(name):'))
})

test('a compact struct with optional fields is unsupported', (t) => {
  try {
    schemaWithStruct().toCode()
    t.fail('expected UNSUPPORTED_TYPE')
  } catch (err) {
    t.is(err.code, 'UNSUPPORTED_TYPE')
  }
})

test('a compact struct with only required fields generates a codec', (t) => {
  const code = compactStructAllRequired().toCode()
  t.ok(code.includes('class _Encoding0(c.Codec)'), 'emits a struct codec')
  t.ok(code.includes('c.uint'), 'encodes the required uint field')
  t.absent(code.includes('flags ='), 'no flags word for a no-optional struct')
})

test('a sized-int field emits its codec', (t) => {
  t.ok(compactStructWithField('uint24').toCode().includes('c.uint24'))
})

test('a float field emits its codec', (t) => {
  t.ok(compactStructWithField('float64').toCode().includes('c.float64'))
})

test('a fixed field emits its codec', (t) => {
  t.ok(compactStructWithField('fixed32').toCode().includes('c.fixed32'))
})

test('a json field emits its codec', (t) => {
  t.ok(compactStructWithField('json').toCode().includes('c.json'))
})

test('a bool field generates a flag-bit codec', (t) => {
  const code = nonCompactStructWithBool().toCode()
  t.ok(code.includes('bool(flags &'), 'decode reads the bool from the flags word')
  t.absent(code.includes('c.bool'), 'no separate codec byte for a bool field')
})

test('an alias field emits its target codec', (t) => {
  const code = schemaWithAliasField().toCode()
  t.ok(code.includes('c.string'), 'alias-of-string field emits c.string')
})

test('a non-compact nested struct field emits a framed codec', (t) => {
  const code = schemaWithFramedNestedField().toCode()
  t.ok(code.includes('c.frame(_encoding'), 'framed nested emits c.frame(_encoding..)')
})

test('a compact nested struct field emits an inline codec reference', (t) => {
  const code = schemaWithInlineNestedField().toCode()
  t.absent(code.includes('c.frame'), 'compact nested is not framed')
  t.ok(
    /_encoding\d+\.(preencode|encode|decode)\(state/.test(code),
    'inline nested references _encoding directly'
  )
})

test('a top-level array of a primitive emits c.array', (t) => {
  const code = schemaWithArrayOfPrimitive().toCode()
  t.ok(code.includes('c.array(c.uint)'), 'array of uint emits c.array(c.uint)')
})

test('a top-level array of a compact struct emits an inline c.array', (t) => {
  const code = schemaWithArrayOfStruct().toCode()
  t.ok(/c\.array\(_encoding\d+\)/.test(code), 'array of compact struct emits c.array(_encoding..)')
  t.absent(code.includes('c.array(c.frame'), 'compact struct element is not framed')
})

test('a top-level record of primitives emits c.record', (t) => {
  const code = schemaWithRecordOfPrimitives().toCode()
  t.ok(
    code.includes('c.record(c.string, c.uint)'),
    'record of string->uint emits c.record(c.string, c.uint)'
  )
})

test('a top-level record with a compact-struct value emits an inline value', (t) => {
  const code = schemaWithRecordOfStructValue().toCode()
  t.ok(/c\.record\(c\.string, _encoding\d+\)/.test(code), 'record value is an inline _encoding ref')
  t.absent(code.includes('c.record(c.string, c.frame'), 'compact-struct value is not framed')
})

test('toDisk writes both files for an empty schema', (t) => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'hsp-'))
  PythonHyperschema.toDisk(emptySchema(), dir)
  t.ok(fs.existsSync(path.join(dir, 'schema.json')))
  t.ok(fs.existsSync(path.join(dir, 'schema.py')))
})

test('toDisk writes nothing when generation throws', (t) => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'hsp-'))
  try {
    PythonHyperschema.toDisk(schemaWithStruct(), dir)
    t.fail('expected throw')
  } catch (err) {
    t.is(err.code, 'UNSUPPORTED_TYPE')
  }
  t.absent(fs.existsSync(path.join(dir, 'schema.json')))
  t.absent(fs.existsSync(path.join(dir, 'schema.py')))
})
