const test = require('brittle')
const fs = require('fs')
const os = require('os')
const path = require('path')
const PythonHyperschema = require('..')

function emptySchema() {
  return new PythonHyperschema(null, {})
}

function schemaWithStruct() {
  const hs = new PythonHyperschema(null, {})
  const ns = hs.namespace('ns')
  ns.register({
    name: 'item',
    compact: true,
    fields: [{ name: 'id', type: 'uint', required: false }]
  })
  return hs
}

function compactStructAllRequired() {
  const hs = new PythonHyperschema(null, {})
  const ns = hs.namespace('ns')
  ns.register({
    name: 'item',
    compact: true,
    fields: [{ name: 'id', type: 'uint', required: true }]
  })
  return hs
}

function compactStructWithField(typeName) {
  const hs = new PythonHyperschema(null, {})
  hs.namespace('ns').register({
    name: 'item',
    compact: true,
    fields: [{ name: 'v', type: typeName, required: true }]
  })
  return hs
}

function nonCompactStructWithBool() {
  const hs = new PythonHyperschema(null, {})
  hs.namespace('ns').register({
    name: 'b',
    compact: false,
    fields: [{ name: 'flag', type: 'bool', required: false }]
  })
  return hs
}

test('empty schema emits header + resolve', (t) => {
  const code = emptySchema().toCode()
  t.ok(code.includes('autogenerated by the hyperschema-python compiler'))
  t.ok(code.includes('import compact_encoding as c'))
  t.ok(code.includes('def resolve(name):'))
})

test('a compact struct with optional fields is unsupported', (t) => {
  try {
    schemaWithStruct().toCode()
    t.fail('expected UNSUPPORTED_TYPE')
  } catch (err) {
    t.is(err.code, 'UNSUPPORTED_TYPE')
  }
})

test('a compact struct with only required fields generates a codec', (t) => {
  const code = compactStructAllRequired().toCode()
  t.ok(code.includes('class _Encoding0(c.Codec)'), 'emits a struct codec')
  t.ok(code.includes('c.uint'), 'encodes the required uint field')
  t.absent(code.includes('flags ='), 'no flags word for a no-optional struct')
})

test('a sized-int field emits its codec', (t) => {
  t.ok(compactStructWithField('uint24').toCode().includes('c.uint24'))
})

test('a float field emits its codec', (t) => {
  t.ok(compactStructWithField('float64').toCode().includes('c.float64'))
})

test('a fixed field emits its codec', (t) => {
  t.ok(compactStructWithField('fixed32').toCode().includes('c.fixed32'))
})

test('a bool field generates a flag-bit codec', (t) => {
  const code = nonCompactStructWithBool().toCode()
  t.ok(code.includes('bool(flags &'), 'decode reads the bool from the flags word')
  t.absent(code.includes('c.bool'), 'no separate codec byte for a bool field')
})

test('toDisk writes both files for an empty schema', (t) => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'hsp-'))
  PythonHyperschema.toDisk(emptySchema(), dir)
  t.ok(fs.existsSync(path.join(dir, 'schema.json')))
  t.ok(fs.existsSync(path.join(dir, 'schema.py')))
})

test('toDisk writes nothing when generation throws', (t) => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'hsp-'))
  try {
    PythonHyperschema.toDisk(schemaWithStruct(), dir)
    t.fail('expected throw')
  } catch (err) {
    t.is(err.code, 'UNSUPPORTED_TYPE')
  }
  t.absent(fs.existsSync(path.join(dir, 'schema.json')))
  t.absent(fs.existsSync(path.join(dir, 'schema.py')))
})
