const test = require('brittle')
const fs = require('fs')
const os = require('os')
const path = require('path')
const PythonHyperschema = require('..')

function emptySchema() {
  return new PythonHyperschema(null, {})
}

function schemaWithStruct() {
  const hs = new PythonHyperschema(null, {})
  const ns = hs.namespace('ns')
  ns.register({ name: 'item', fields: [{ name: 'id', type: 'uint', required: true }] })
  return hs
}

test('empty schema emits header + resolve', (t) => {
  const code = emptySchema().toCode()
  t.ok(code.includes('autogenerated by the hyperschema-python compiler'))
  t.ok(code.includes('import compact_encoding as c'))
  t.ok(code.includes('def resolve(name):'))
})

test('a declared struct is unsupported until its emitter lands', (t) => {
  try {
    schemaWithStruct().toCode()
    t.fail('expected UNSUPPORTED_TYPE')
  } catch (err) {
    t.is(err.code, 'UNSUPPORTED_TYPE')
  }
})

test('toDisk writes both files for an empty schema', (t) => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'hsp-'))
  PythonHyperschema.toDisk(emptySchema(), dir)
  t.ok(fs.existsSync(path.join(dir, 'schema.json')))
  t.ok(fs.existsSync(path.join(dir, 'schema.py')))
})

test('toDisk writes nothing when generation throws', (t) => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'hsp-'))
  try {
    PythonHyperschema.toDisk(schemaWithStruct(), dir)
    t.fail('expected throw')
  } catch (err) {
    t.is(err.code, 'UNSUPPORTED_TYPE')
  }
  t.absent(fs.existsSync(path.join(dir, 'schema.json')))
  t.absent(fs.existsSync(path.join(dir, 'schema.py')))
})
