const errors = require('./errors')

module.exports = function generatePython(hyperschema) {
  hyperschema.linkAll()

  const positionByFqn = new Map()
  for (let i = 0; i < hyperschema.schema.length; i++) {
    positionByFqn.set(hyperschema.typesByPosition.get(i), i)
  }

  const blocks = []
  const registry = []

  for (let i = 0; i < hyperschema.schema.length; i++) {
    const fqn = hyperschema.typesByPosition.get(i)
    const type = hyperschema.resolve(fqn)
    // An alias is a name for its target type, not a type with its own wire
    // encoding, so it gets no _encoding class or registry entry. Fields of
    // alias type resolve straight through to the target (see resolveAlias).
    if (type.isAlias) continue
    if (type.isEnum) {
      blocks.push(...generateEnum(type, i))
    } else if (type.isStruct && (!type.compact || type.flagsPosition === -1)) {
      blocks.push(...generateStruct(type, i, positionByFqn))
    } else if (type.isArray) {
      blocks.push(...generateArray(type, i, positionByFqn))
    } else if (type.isRecord) {
      blocks.push(...generateRecord(type, i, positionByFqn))
    } else {
      throw errors.UNSUPPORTED_TYPE(fqn, constructKind(type))
    }
    registry.push(`    ${JSON.stringify(fqn)}: _encoding${i},`)
  }

  const header = [
    '# This file is autogenerated by the hyperschema-python compiler',
    '# !!DO NOT EDIT THIS FILE!!',
    `# Schema Version: ${hyperschema.version}`,
    '',
    'import compact_encoding as c',
    ''
  ]

  const footer = [
    '_codecs = {',
    ...registry,
    '}',
    '',
    '',
    'def resolve(name):',
    '    return _codecs[name]'
  ]

  return header.concat(blocks, footer).join('\n') + '\n'
}

const PRIMITIVES = {
  uint: 'c.uint',
  uint32: 'c.uint32',
  int: 'c.int',
  string: 'c.string',
  buffer: 'c.buffer',
  uint8: 'c.uint8',
  uint16: 'c.uint16',
  uint24: 'c.uint24',
  uint40: 'c.uint40',
  uint48: 'c.uint48',
  uint56: 'c.uint56',
  int24: 'c.int24',
  int40: 'c.int40',
  int48: 'c.int48',
  int56: 'c.int56',
  float32: 'c.float32',
  float64: 'c.float64',
  fixed32: 'c.fixed32',
  fixed64: 'c.fixed64',
  json: 'c.json'
}

function resolveAlias(type) {
  while (type.isAlias) type = type.type
  return type
}

function typeCodec(type, positionByFqn) {
  type = resolveAlias(type)
  if (type.isEnum || type.isStruct) return `_encoding${positionByFqn.get(type.fqn)}`
  const prim = PRIMITIVES[type.name]
  if (!prim) throw errors.UNSUPPORTED_TYPE(type.name, 'primitive')
  return prim
}

function fieldCodec(field, positionByFqn) {
  if (field.array) throw errors.UNSUPPORTED_TYPE(field.name, 'array field')
  const type = resolveAlias(field.type)
  const codec = typeCodec(field.type, positionByFqn)
  if (type.isStruct && field.framed) return `c.frame(${codec})`
  return codec
}

function presence(field) {
  const key = JSON.stringify(field.name)
  const type = resolveAlias(field.type)
  // A JS Buffer is truthy even when empty, so buffer presence is is-not-None.
  // json and struct fields are is-not-None too: JS objects/arrays ({}, []) and
  // struct dicts are truthy (present) but falsy in Python when empty, so
  // truthiness would wrongly drop them. Scalar/enum optionals follow JS
  // truthiness. Aliases resolve to their target type first.
  if (type.name === 'buffer' || type.name === 'json' || type.isStruct) {
    return `m.get(${key}) is not None`
  }
  return `m.get(${key})`
}

function defaultFor(field) {
  const type = resolveAlias(field.type)
  if (type.isEnum) return type.strings ? 'None' : '0'
  if (type.isStruct || type.name === 'string' || type.name === 'buffer' || type.name === 'json') {
    return 'None'
  }
  return '0'
}

function generateStruct(struct, index, positionByFqn) {
  const fields = struct.fields
  const flagsPosition = struct.flagsPosition
  const hasFlags = flagsPosition !== -1
  const preEnd = hasFlags ? flagsPosition : fields.length

  const lines = [`class _Encoding${index}(c.Codec):  # ${struct.fqn}`]

  for (const fn of ['preencode', 'encode']) {
    lines.push(`    def ${fn}(self, state, m):`)
    const body = []
    for (let i = 0; i < preEnd; i++) {
      const f = fields[i]
      body.push(
        `        ${fieldCodec(f, positionByFqn)}.${fn}(state, m[${JSON.stringify(f.name)}])`
      )
    }
    if (hasFlags) {
      const optionals = []
      for (let i = flagsPosition; i < fields.length; i++) {
        if (!fields[i].required) optionals.push(fields[i])
      }
      const terms = optionals.map((f) => `(${f.flag} if ${presence(f)} else 0)`)
      body.push(`        flags = ${terms.length ? terms.join(' | ') : '0'}`)
      body.push(`        c.uint.${fn}(state, flags)`)
      for (let i = flagsPosition; i < fields.length; i++) {
        const f = fields[i]
        if (f.type.name === 'bool') continue
        const key = JSON.stringify(f.name)
        if (f.required) {
          body.push(`        ${fieldCodec(f, positionByFqn)}.${fn}(state, m[${key}])`)
        } else {
          body.push(`        if ${presence(f)}:`)
          body.push(`            ${fieldCodec(f, positionByFqn)}.${fn}(state, m[${key}])`)
        }
      }
    }
    if (body.length === 0) body.push('        pass')
    lines.push(...body)
    lines.push('')
  }

  lines.push('    def decode(self, state):')
  const keys = []
  for (let i = 0; i < preEnd; i++) {
    const f = fields[i]
    lines.push(`        v${i} = ${fieldCodec(f, positionByFqn)}.decode(state)`)
    keys.push([f.name, `v${i}`])
  }
  if (hasFlags) {
    lines.push('        flags = c.uint.decode(state) if state.start < state.end else 0')
    for (let i = flagsPosition; i < fields.length; i++) {
      const f = fields[i]
      if (f.type.name === 'bool') {
        lines.push(`        v${i} = bool(flags & ${f.flag})`)
        keys.push([f.name, `v${i}`])
        continue
      }
      if (f.required) {
        lines.push(`        v${i} = ${fieldCodec(f, positionByFqn)}.decode(state)`)
      } else {
        lines.push(
          `        v${i} = ${fieldCodec(f, positionByFqn)}.decode(state) if (flags & ${f.flag}) else ${defaultFor(f)}`
        )
      }
      keys.push([f.name, `v${i}`])
    }
  }
  lines.push('        return {')
  for (const [name, ref] of keys) {
    lines.push(`            ${JSON.stringify(name)}: ${ref},`)
  }
  lines.push('        }')
  lines.push('')
  lines.push(`_encoding${index} = _Encoding${index}()`)
  lines.push('')
  return lines
}

function generateEnum(type, index) {
  const variants = type.enum
  const offset = type.offset ?? 1
  const lines = []

  if (type.strings) {
    const values = variants.map((v, i) => `${JSON.stringify(v.key)}: ${offset + i}`).join(', ')
    const keys = variants.map((v, i) => `${offset + i}: ${JSON.stringify(v.key)}`).join(', ')
    lines.push(`_encoding${index}_values = {${values}}  # ${type.fqn}`)
    lines.push(`_encoding${index}_keys = {${keys}}`)
    lines.push('')
    lines.push(`class _Encoding${index}(c.Codec):`)
    lines.push('    def preencode(self, state, m):')
    lines.push(`        c.uint.preencode(state, _encoding${index}_values[m])`)
    lines.push('    def encode(self, state, m):')
    lines.push(`        c.uint.encode(state, _encoding${index}_values[m])`)
    lines.push('    def decode(self, state):')
    lines.push(`        return _encoding${index}_keys[c.uint.decode(state)]`)
  } else {
    // Numeric enum: the value is the integer, encoded directly (JS behavior).
    lines.push(`class _Encoding${index}(c.Codec):  # ${type.fqn}`)
    lines.push('    def preencode(self, state, m):')
    lines.push('        c.uint.preencode(state, m)')
    lines.push('    def encode(self, state, m):')
    lines.push('        c.uint.encode(state, m)')
    lines.push('    def decode(self, state):')
    lines.push('        return c.uint.decode(state)')
  }

  lines.push('')
  lines.push(`_encoding${index} = _Encoding${index}()`)
  lines.push('')
  return lines
}

function generateArray(type, index, positionByFqn) {
  const elem = typeCodec(type.type, positionByFqn)
  const enc = type.framed ? `c.frame(${elem})` : elem
  return [`_encoding${index} = c.array(${enc})`, '']
}

function generateRecord(type, index, positionByFqn) {
  const keyEnc = typeCodec(type.key, positionByFqn)
  const valueEnc = typeCodec(type.value, positionByFqn)
  return [`_encoding${index} = c.record(${keyEnc}, ${valueEnc})`, '']
}

function constructKind(type) {
  if (type.isArray) return 'array'
  if (type.isRecord) return 'record'
  if (type.isVersioned) return 'versioned type'
  if (type.isExternal) return 'external type'
  if (type.isStruct && type.compact) return 'compact struct with optional fields'
  return 'type'
}
